/** Canonical app paths — no expo-router route-group parentheses. */
export const routes = {
  root: '/',
  auth: '/auth',
  authPhone: '/auth/phone',
  authCallback: '/auth/callback',
  onboardingVenue: '/onboarding/venue',
  onboardingMode: '/onboarding/mode',
  onboardingCheckIn: '/onboarding/check-in',
  onboardingProfile: '/onboarding/profile',
  onboardingPeer: '/onboarding/peer/[userId]',
  onboardingVenueRoom: '/onboarding/venue/[venueId]/room',
  onboardingVenueDetail: '/onboarding/venue/[venueId]',
  mainHome: '/main/tabs/home',
  mainInbox: '/main/tabs/inbox',
  mainMap: '/main/tabs/map',
  mainProfile: '/main/tabs/profile',
  mainRoom: '/main/room',
  mainChat: '/main/chat/[connectionId]',
  mainVenueDetail: '/main/venue/[venueId]',
  mainArchived: '/main/archived',
  mainReport: '/main/report',
  mainPeer: '/main/peer/[userId]',
} as const;
